const albums = [
  {year:2013, slug:'2013-treci-album', title:'Treći album', cover:'images/albums/treci-album.jpg', tracks:['Devojka iz Zagreba','Lepota','Matori podlače','Postoje neki ljudi','Ruke u tami','Sivi dan','Sviđaš mi se ti','Vila','Vronski','Život u tvornici']},
  {year:2012, slug:'2012-protiv-tebe', title:'Protiv tebe', cover:'images/albums/protiv-tebe.jpg', tracks:['1994','Ekumena','Jebeni grad','Mali','Moje vreme prošlo','Obnova i izgradnja','Ona živi na rubu','Pesnik','Pevam','Sloboda','Vasiona']},
  {year:2011, slug:'2011-pored-vatre', title:'Pored vatre', cover:'images/albums/pored-vatre.jpg', tracks:['Bez poverenja','Fini mladi ljudi','Mlade mame','Moja država','Negde','Noć pod nebom','Položaj čoveka','Poznanja','Sunce sija u našem kraju','Uspavanka za Iskru (rmx)','Uspavanka za Iskru','Zastor','Znam taj dan']},
  {year:2009, slug:'2009-u-potrazi-za-bendom', title:'U potrazi za bendom', cover:'images/albums/u-potrazi-za-bendom.jpg', tracks:['1994','Besplatna pesma','Bez poverenja','Fini mladi ljudi','Ja sam bogat','Mlade mame','Mladi filozof je postao kamen','Sve i svja','Udvoje','Uspavanka za iskru','Vasiona','Znam taj dan']}
];
const photos = [
  ['rlz-bend-2026.jpg','Resnik leta 2026'],['proba-rlz-2026.jpg','Proba, 2026'],['damjan-studio-2026.jpg','Studio, 2026'],
  ['zorica-proba-2013.jpg','Proba, 2013'],['svirka-bigz-pavi-2013.jpg','Svirka u BIGZ-u, 2013'],['svirka-bigz-2013.jpg','BIGZ scena, 2013'],['svirka-bigz-2013-1.jpg','BIGZ scena, 2013'],['svirka-bigz-2013-2.jpg','BIGZ scena, 2013'],['svirka-bigz-2013-3.jpg','BIGZ scena, 2013'],['svirka-bigz-2013-4.jpg','BIGZ scena, 2013'],['svirka-bigz-2013-krle-dule-zorica.jpg','BIGZ scena, 2013'],['pavi-proba-2013.jpg','Proba, 2013'],['proba-kod-filipa-2013.jpg','Proba kod Filipa, 2013'],['publika-bigz-2013.jpg','Publika, BIGZ 2013'],
  ['svirka-zica-2011.jpg','Svirka u Žici, 2011'],['pored-vatre-cd-2011.jpg','Pored vatre, 2011'],['pored-vatre-cd-2-2011.jpg','Pored vatre, 2011'],['javna-proba-zica-2011.jpg','Javna proba u Žici, 2011'],['damjan-svirka-bigz-petrovic-2011.jpg','Svirka u BIGZ-u, 2011'],['damjan-od-resnika-prnjavorstock-2011.jpg','Prnjavorstock, 2011'],['damjan-od-resnika-prnjavorstock-2011-1.jpg','Prnjavorstock, 2011'],['damjan-od-resnika-prnjavorstock-2011-2.jpg','Prnjavorstock, 2011'],['damjan-od-resnika-prnjavorstock-2011-3.jpg','Prnjavorstock, 2011'],['damjan-od-resnika-prnjavorstock-2011-4.jpg','Prnjavorstock, 2011'],
  ['zagrađe-leto-2010.jpg','Zagrađe, leto 2010'],['zagradje-pored-vatre-2010.jpg','Zagrađe, 2010'],['violina-prnjavor-2010.jpg','Prnjavor, 2010'],['violina-prnjavor-2010-2.jpg','Prnjavor, 2010'],['violina-peva-prnjavor-2010.jpg','Prnjavor, 2010'],['violina-peva-prnjavor-2010-2.jpg','Prnjavor, 2010'],['violina-bakal-prnjavor-2010.jpg','Prnjavor, 2010'],['svirka-zica-2010.jpg','Žica, 2010'],['svirka-zica-2010-2.jpg','Žica, 2010'],['svirka-zica-2010-3.jpg','Žica, 2010'],['svirka-obrenovac-2010.jpg','Svirka u Obrenovcu, 2010'],['kriva-i-violina-prnjavor-2010.jpg','Prnjavor, 2010'],['kriva-i-violina-prnjavor-2010-2.jpg','Prnjavor, 2010'],['damjan-od-resnika-prnjavorstock-2010-tonska-proba.jpg','Tonska proba, Prnjavorstock 2010'],['damjan-od-resnika-prnjavor-2010.jpg','Prnjavorstock, 2010'],['damjan-od-resnika-prnjavor-2010-1.jpg','Prnjavorstock, 2010'],['damjan-od-resnika-prnjavor-2010-2.jpg','Prnjavorstock, 2010'],['damjan-od-resnika-prnjavor-2010-3.jpg','Prnjavorstock, 2010'],['damjan-od-resnika-prnjavor-2010-4.jpg','Prnjavorstock, 2010'],['damjan-od-resnika-prnjavor-2010-5.jpg','Prnjavorstock, 2010'],['damjan-od-resnika-prnjavor-2010-6.jpg','Prnjavorstock, 2010'],['damjan-od-resnika-prnjavor-2010-7.jpg','Prnjavorstock, 2010'],['damjan-od-resnika-prnjavor-2010-8.jpg','Prnjavorstock, 2010'],['bakal-prnjavor-2010.jpg','Prnjavor, 2010'],['bakal-svirka-zica-2010.jpg','Žica, 2010'],['bakal-zagradje-2010.jpg','Zagrađe, 2010'],
  ['tusta-i-tma-2009.jpg','Tušta i tma, 2009'],['tusta-i-tma-band-smeh-2009.jpg','Tušta i tma, 2009'],['tusta-i-tma-bend-2009.jpg','Tušta i tma, 2009'],['tusta-i-tma-bigz-2009.jpg','Tušta i tma u BIGZ-u, 2009'],['svirka-skc-2009.jpg','Svirka u SKC-u, 2009'],['damjan-od-resnika-svirka-skc-2009.jpg','Svirka u SKC-u, 2009'],['damjan-bigz-2009.jpg','Vežbanje u BIGZ-u, 2009'],['damjan-od-resnika-gavez-2009.jpg','Festivalit u Gavezu, 2009']
];
const allTracks = albums.flatMap(album => album.tracks.map(title => ({...album,title,path:`music/${album.slug}/Damjan od Resnika - ${title}.mp3`})));
const albumContainer = document.querySelector('#albums');
const gallery = document.querySelector('#gallery-grid');
const audio = document.querySelector('#audio');
const nowPlaying = document.querySelector('#now-playing');
let current = null, played = [];
const esc = text => text.replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
if (albumContainer) albumContainer.innerHTML = albums.map(album => `<article class="album"><img class="cover" src="${album.cover}" alt="Omot albuma ${album.title}"><div><h3 class="album-title">${album.title}</h3><p class="album-year">${album.year}</p><a class="download" href="https://github.com/mudroljub/damjan-od-resnika/releases" target="_blank" rel="noopener">Preuzmi album (ZIP)</a><ol class="tracks">${album.tracks.map((track,index) => `<li class="track" data-path="music/${album.slug}/Damjan od Resnika - ${esc(track)}.mp3"><span class="track-number">${String(index+1).padStart(2,'0')}</span><button class="play-track" type="button">${esc(track)}</button><span class="track-mark">●</span></li>`).join('')}</ol></div></article>`).join('');
if (gallery) gallery.innerHTML = photos.map(([file,caption]) => `<figure class="gallery-item"><img loading="lazy" src="images/musicians/${file}" alt="${caption}"><figcaption>${caption}</figcaption></figure>`).join('');
function play(track) { current = track; audio.src = track.path; audio.play(); nowPlaying.textContent = `${track.title} — ${track.title ? track.year : ''}`; document.querySelectorAll('.track').forEach(item => item.classList.toggle('active', item.dataset.path === track.path)); document.querySelector('#main-play').textContent = '❚❚'; }
function nextTrack() { if (played.length === allTracks.length) played = []; const choices = allTracks.filter(track => !played.includes(track.path)); const track = choices[Math.floor(Math.random()*choices.length)]; played.push(track.path); play(track); }
if (audio) { document.querySelectorAll('.play-track').forEach(button => button.addEventListener('click', () => { const path = button.closest('.track').dataset.path; play(allTracks.find(track => track.path === path)); })); document.querySelector('#shuffle').addEventListener('click', nextTrack);document.querySelector('#next').addEventListener('click', nextTrack);audio.addEventListener('ended',nextTrack);document.querySelector('#main-play').addEventListener('click', () => { if (!current) return nextTrack(); if(audio.paused) { audio.play(); document.querySelector('#main-play').textContent='❚❚'; } else { audio.pause(); document.querySelector('#main-play').textContent='▶'; } }); }
